[package]
authors = ["Alex Whitney <adwhit@fastmail.com>"]
name = "openapi3"
version = "0.1.0"
edition = "2018"

[dependencies]
error-chain = "0.12"
regex = "1.3.3"
schemafy = "0.3"
serde_derive = "1"
serde_json = "1.0.2"
serde_yaml = "0.8"

[dependencies.serde]
features = ["rc"]
version = "1"
